### ISSUE TITLE
Highlighting

### ISSUE THREAD

**Issue by atr0p1ne** [nickeb96/fish.vim#1]
Hi, 

thank you for making this extension, can you review this little issue?

#!/usr/bin/fish
set FruitPicker "apple"

if test $FruitPicker = "pear"
    echo "You picked Pear"
else
    echo "Try again"
end

Everything after "pear" is displayed in wrong colors.
You can fix it when you don't use quotes, but i want to use them because i have space in that variable.

**Comment by nickeb96** [comment]
It looks like the `=` sign wasn't being recognized as an argument, which caused the syntax highlighter to not know what to do with the rest of the line.  It also wasn't recognizing commands like `g++` properly because of the `+` signs.

The latest commit b24d0849c8b4321bd31e7efd788f886ae2592017 should have fixed all of that, so give it a try and let me know if it worked for you too.
